name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
    inputs:
      apiToken:
        description: "Astro API Token"
        required: true
        type: string
      deploymentId:
        description: "Deployment to push DAGs to"
        required: true
        type: string
#  push:
#    branches:
#      - main

env:
  ## Sets Deployment API credentials as environment variables
  # ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
  ASTRO_API_TOKEN: ${{ inputs.apiToken }}
  DEPLOYMENT_ID: ${{ inputs.deploymentId }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.2
